### ISSUE TITLE
Cant upload .bashrc Trusty host

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#27]
getting this error

Running provisioner: file...
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /home/niccolox/.bashrc
Dest: /home/vagrant/.bashrc

**Comment by niccolox** [comment]
got passed this with

vagrant ssh
sudo chmod 777 /tmp
exit
vagrant reload --provision
https://github.com/mitchellh/vagrant/issues/2804

**Comment by niccolox** [comment]
you might want to bypass some of the nfs related issues with https://github.com/gael-ian/vagrant-bindfs

**Comment by ghost** [comment]
I confirm the error in current HEAD, and the solution.

Thank you niccolox.

**Comment by niccolox** [comment]
I read its possible to install Virtualbox & Vagrant on a guest OS inside VmWare (and I guess KVM) and test different linux (and Windows) versions of the system

its tempting, Vagrant doesnt play nice with Linux imho (Vagrant lead Mitchell only tests on Mac and Windows) and Vagrant introduces all sorts of instability on my Trusty box

anyways... I digress

**Comment by MatthewHager** [comment]
The current version is a bit unstable but I know @ergonlogic does his primary dev on a Linux box so when we get this more stable (should be next week) you shouldn't have any trouble on Linux.

**Comment by ergonlogic** [comment]
In one of the plugins we use, we're switching to the `ubuntu` user to move some users and groups around. This is to allow for the host user's uid/gid to match those of the `aegir` user and the `www-data` group. This, in turn, allows proper NFS permissions both on the host and in the VM.

I believe the issue here is that `/vagrant` and a few other locations end up being owned by `ubuntu` instead of `vagrant`. This is a bug in https://github.com/GetValkyrie/valkyrie-mount, the aforementioned plugin. The work-around that I've been using is to add the following to the Vagrantfile:

```
  config.ssh.username = 'ubuntu'
```

I've also been commenting out the entire block of dotfile provisioning because of such permissions issues. Once the bug is fixed in the plugin, these parts should work again. I'll probably be moving the dotfile provisioning into a plugin too, for easier isolated testing.

**Comment by ergonlogic** [comment]
Also, I'm considering deprecating dotfile provisioning entirely. One of the main goals of Valkyrie is to allow editing of code and operation of local dev sites _from the host machine_. This makes dotfiles in the VM a moot point.

**Comment by MatthewHager** [comment]
I vote for removing it. It's one more thing we'll have to maintain.

**Comment by niccolox** [comment]
I use ZSH anyways, so no .bashrc, I actually switched back to Bash from zsh to try to make this work... 

kiss

**Comment by ergonlogic** [comment]
I removed the dotfile handling altogether. I'll work on the underlying issue in https://github.com/GetValkyrie/valkyrie-mount/issues/1
