### ISSUE TITLE
feature request: drush vnew valkyrie 1.2.3.4:8888

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#40]
would be nice to be able to specifiy a static IP (even private but static IP) and port at project creation time

I went looking for IP to change but found 2 (or 3) Vagrantfile and config.yml and when I did change it clashed with VB private networks

I ended up leaving IP alone and created port forwarding for http (complimenting ssh)

I run Vagrant on a server in a separate building and connect over the lan from various laptops

**Comment by ergonlogic** [comment]
We do specify a static IP, `10.42.0.10`. You can specify an alternative IP address to use by creating a file called `config.yml` in the project root and adding:

```
ip: 1.2.3.4
```

Obviously, you'd need to run `vagrant reload` for this to take effect. Alternatively, `drush vnew --up=0` will initialize the project, but not launch the VM. This allows you to customize it as you'd like.

We don't use port-forwarding for http, since we provide DNS-based solutions; on Linux, Avahi-announced mDNS, and on OSX we use the vagrant-dns plugin.

Valkyrie is really designed to run Vagrant on your local machine. I don't know that we'll be able to support the remote Vagrant setup you describe.

**Comment by niccolox** [comment]
yeah, I know, I could try Vagrant Share, or Localtunnel or Ngrok ... 

but for now, port-forwarding manually, in VB networking works fine.. do have to do /etc/hosts hacks also... 

it might also come down to a more sophisticated LAN, I am trying to get around to using pfsense and not the limited ISP router
