### ISSUE TITLE
`drush vpa` doesn't properly detect added profiles

### ISSUE THREAD

**Issue by MatthewHager** [GetValkyrie/valkyrie#8]
I just cloned rune and then did a `vpa` and it registered the platform but the rune install profile didn't show up. If I create the platform through the UI the profile does show up.

**Comment by ergonlogic** [comment]
I've added a provision-verify, so that the platform's drushrc.php is populated with the list of projects prior to importing into the front-end.

**Comment by ergonlogic** [comment]
nope, it looks like the problem was that drush_invoke_process() was mangling the options passed to hosting-import. In my testing, the platform path was always over-written as /var/aegir/hostmaster-7.x-3.x. I fixed it by simply switching to drush_shell_exec(). Eventually, it'd be good to fix Drush's handling of this, but that'll have to wait.
