### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by zanami** [GetValkyrie/valkyrie#92]
I've finally managed to install Valkirie and it's almost what I was looking for except...
1. Installation isn't easy and requires some vagrant ssh & apt-get install magic.
2. There's no Drupal 8 support (drush 7).
3. Docs are confusing and almost non-existent, different parts list different requirements etc. I'm kind of familiar with Aegir yet It's not completely clear what are the benefits of Valkyrie.

I guess it's a great tool for those who built and use it, but it's not very straightforward for those out of context. I'd like to know is there any plans, a roadmap or something.
Thanks!

**Comment by MatthewHager** [comment]
We've actually started working on a new project that achieves the same goal but is build for Drupal 8 and a composer based workflow. You can view that project here: https://github.com/poetic/nebula.

It is unstable at the moment and likely has issues, but we'll be resuming work on that project and most likely won't be putting much more work towards this one. Nebula doesn't have Aegir but does have directory mounting/sharing between the host/guest like this project has. It also automatically configures sitename.local avahi aliases so that you don't need to configure DNS entries.

I recommend following the nebula project and we'll update the README as we make progress there. I would continue to use this for d7 and use nebula for d8.

**Comment by MatthewHager** [comment]
@zanami if you're interested in syncing about what the "ultimate drupal dev environment" would be, perhaps you could help out/team up with us. We've got Valkyrie and a good rewrite going with Nebula, we just need a little extra nudge to get it rolling. Let me know if you'd be interested in contributing. If so, I'll give you a demo of what we've got for nebula and then we can make a wish list for future items.

**Comment by ergonlogic** [comment]
Yep, Valkyrie is essentially seeking co-maintainers at this point. I've updated the d.o project page to clarify this.

For my part, I've been working on a new replacement project too, based on GNU Make: http://drumk.it/. The docs are a bit out-of-date, but should receive a refresh in the next couple days. I've been using Drumkit as the basis for a number of projects recently, from building a new Drupal distribution, to managing cloud infrastructure with Ansible. It's under heavy development, but there's reasonable test coverage.

It takes a very different approach from Valkyrie, but one that I believe makes it much more flexible. Instead of having a global install, and then creating/managing projects from there, Drumkit is embedded into projects individually, as a git submodule. It then downloads local versions of various tools (composer, behat, ansible, etc.) This allows a distributed team to work on a common set of tools on a _per project_ basis.

I've actually found that Vagrant is mostly unnecessary, which is why there's currently only rudimentary support for it. Of course, this leads to additional dependencies on localhost. I'm undecided on whether running everything inside Vagrant is really worthwhile, considering the additional overhead. Also, CI testing of anything that interacts with Vagrant is quite challenging.

Anyway, you might also be interested in Acquia's new toolkit: https://github.com/acquia/blt.

**Comment by zanami** [comment]
Thanks guys. I'm at this point would not be of much use as a contributor. Maybe a tester at most. I have some experience (from user perspective) with [Kalabox](http://www.kalabox.io), Valkyrie and some other less known development environments.

Almost all of them are vagrant/virtualbox based solutions with NFS, rsync (or syncthing) host-guest folders sharing/syncing. Also most of them presume you're building a single large and serious project which is not my case as I support a bunch of various (D6-D8) smaller projects.

The problem is performance in my case. Kalabox (virtualbox headless + syncthing) consumes up to 100% CPU idling. It's just plain uncomfortable. Valkyrie is significantly better in this respect but it uses NFS which isn't very fast so drush cr takes up to 30-50 seconds.

As of now I think [this kind](https://www.chapterthree.com/blog/drupal-development-docker-compose) of Docker Composer based solution is the way to go for me. It still requires virtualbox on Mac though. There's a [private beta 'native' Docker version](https://blog.docker.com/2016/03/docker-for-mac-windows-beta/) for OS X and Windows so I'll wail until it goes public anyway.
